import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import GlobalNavbar from "@/components/navbar/GlobalNavbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Footer } from "@/components/footer";

import { MeshBackground } from "@/app/DynamicMeshBackground";
import GlopalFooter from "@/components/navbar/glopa-footer";
import { Providers } from "@/lib/proviers/queryClient";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>

          <div className="relative flex min-h-screen flex-col">
            <Providers>
              <GlobalNavbar />
              {children}
              <GlopalFooter />
            </Providers>
          </div>

        </ThemeProvider>
      </body>
    </html >
  );
}
